# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 1049)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, -10, 1680, 1050))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.menu = QtWidgets.QWidget()
        self.menu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menu.setObjectName("menu")
        self.intro_bt = QtWidgets.QPushButton(self.menu)
        self.intro_bt.setGeometry(QtCore.QRect(240, 465, 240, 120))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.intro_bt.setFont(font)
        self.intro_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.intro_bt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.intro_bt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.intro_bt.setObjectName("intro_bt")
        self.member_bt = QtWidgets.QPushButton(self.menu)
        self.member_bt.setGeometry(QtCore.QRect(720, 465, 240, 120))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.member_bt.setFont(font)
        self.member_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.member_bt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.member_bt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.member_bt.setObjectName("member_bt")
        self.achive_bt = QtWidgets.QPushButton(self.menu)
        self.achive_bt.setGeometry(QtCore.QRect(1200, 465, 240, 120))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.achive_bt.setFont(font)
        self.achive_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.achive_bt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.achive_bt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.achive_bt.setObjectName("achive_bt")
        self.main_bg = QtWidgets.QWidget(self.menu)
        self.main_bg.setGeometry(QtCore.QRect(0, 0, 1680, 1050))
        self.main_bg.setStyleSheet("background-image: url(:/background/배경.png);")
        self.main_bg.setObjectName("main_bg")
        self.main_bg.raise_()
        self.intro_bt.raise_()
        self.intro_bt.raise_()
        self.intro_bt.raise_()
        self.intro_bt.raise_()
        self.intro_bt.raise_()
        self.intro_bt.raise_()
        self.member_bt.raise_()
        self.member_bt.raise_()
        self.member_bt.raise_()
        self.achive_bt.raise_()
        self.achive_bt.raise_()
        self.achive_bt.raise_()
        self.achive_bt.raise_()
        self.stackedWidget.addWidget(self.menu)
        self.intro = QtWidgets.QWidget()
        self.intro.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.intro.setObjectName("intro")
        self.esc_1 = QtWidgets.QPushButton(self.intro)
        self.esc_1.setGeometry(QtCore.QRect(10, 10, 100, 100))
        self.esc_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.esc_1.setStyleSheet("background-image: url(:/background/esc.png);\n"
"border: none;")
        self.esc_1.setText("")
        self.esc_1.setObjectName("esc_1")
        self.label = QtWidgets.QLabel(self.intro)
        self.label.setGeometry(QtCore.QRect(590, 360, 511, 311))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.intro)
        self.member = QtWidgets.QWidget()
        self.member.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.member.setObjectName("member")
        self.label_2 = QtWidgets.QLabel(self.member)
        self.label_2.setGeometry(QtCore.QRect(510, 180, 661, 511))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.esc_2 = QtWidgets.QPushButton(self.member)
        self.esc_2.setGeometry(QtCore.QRect(10, 10, 100, 100))
        self.esc_2.setStyleSheet("border-image: url(:/background/esc.png);\n"
"border: none;")
        self.esc_2.setText("")
        self.esc_2.setObjectName("esc_2")
        self.stackedWidget.addWidget(self.member)
        self.achieve = QtWidgets.QWidget()
        self.achieve.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.achieve.setObjectName("achieve")
        self.esc_3 = QtWidgets.QPushButton(self.achieve)
        self.esc_3.setGeometry(QtCore.QRect(10, 10, 100, 100))
        self.esc_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.esc_3.setStyleSheet("background-image: url(:/background/esc.png);\n"
"border: none;")
        self.esc_3.setText("")
        self.esc_3.setObjectName("esc_3")
        self.label_3 = QtWidgets.QLabel(self.achieve)
        self.label_3.setGeometry(QtCore.QRect(600, 340, 381, 341))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.achieve)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.intro_bt.setText(_translate("MainWindow", "ESC 소개"))
        self.member_bt.setText(_translate("MainWindow", "동아리 원"))
        self.achive_bt.setText(_translate("MainWindow", "E.S.C 활동"))
        self.label.setText(_translate("MainWindow", "embedded\n"
"SoftWare\n"
"communication"))
        self.label_2.setText(_translate("MainWindow", "동아리 장: 최승호\n"
"동아리 원: 고정현\n"
"동아리 원: 안소현\n"
"동아리 원: 노시현\n"
"동아리 원: 김해건"))
        self.label_3.setText(_translate("MainWindow", "성과"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

